version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: state_registry_app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
